version: 2.1
orbs:
    aws-cli: circleci/aws-cli@1.0.0

workflows:
    compile-and-push:
        jobs:
            - compile
            - build-and-push:
                context: AWS_CREDS
                requires:
                    - compile
jobs:
  compile:
    docker:
        - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go mod download
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app src/*.go
      - run: mkdir -p workspace
      - run: cp app workspace/
      - run: ls workspace/
      - persist_to_workspace:
            root: workspace
            paths: 
                - app
  
  build-and-push:
    docker:
        - image: circleci/python:latest
    steps:
        - checkout
        - setup_remote_docker
        - attach_workspace:
            at: workspace
        - run: ls
        - run: docker build -t $AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME/go-lambda-proxy:$CIRCLE_BUILD_NUM .
        - run: pip3 install awscli 
        - run: eval "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
        - run: docker push $AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME/go-lambda-proxy:$CIRCLE_BUILD_NUM


