version: 2
jobs:
  build:
    docker: 
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/sharkin104/go-lambda-proxy
    steps:
      - checkout
      - run:
          name: download-libraries
          command: go mod download
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app src/*.go
      - run: ls
    #   - setup_remote_docker:
    #       docker_layer_caching: true
    #   - run: docker build -t ${IMAGE}:$CIRCLE_SHA1 .
    #   - run: echo ${GOOGLE_AUTH} > gcp-key.json
    #   - run: cat "gcp-key.json" | docker login -u _json_key --password-stdin https://eu.gcr.io
    #   - run: docker push ${IMAGE}:$CIRCLE_SHA1