version: 2.1
orbs:
    aws-cli: circleci/aws-cli@1.0.0

workflows:
    compile-and-push:
        jobs:
            - build-source
            - push-ecr
            # - aws-ecr/build-and-push-image:
            #     account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
            #     aws-access-key-id: AWS_ACCESS_KEY_ID
            #     aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            #     context: AWS_CREDS
            #     create-repo: true
            #     dockerfile: Dockerfile
            #     attach-workspace: true
            #     region: AWS_DEFAULT_REGION
            #     repo: go-lambda-proxy
            #     tag: CIRCLE_JOB
            #     workspace-root: workspace
            #     requires:
            #         - build-source
            

jobs:
  build-source:
    docker:
        - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go mod download
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app src/*.go
      - run: mkdir -p workspace
      - run: cp app workspace/
      - run: ls workspace/
      - persist_to_workspace:
            root: workspace
            paths: 
                - app
  
  push-ecr:
    executor: aws-cli/default
    steps:
        - checkout
        - attach_workspace:
            at: /tmp/workspace

